{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a9378e93",
   "metadata": {
    "editable": false,
    "tags": [
     "setup"
    ]
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import torch"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "752cd870",
   "metadata": {},
   "source": [
    "**Dataset**\n",
    "\n",
    "Run the cell below to open and read the ebook of [_Pride and Prejudice_](https://www.gutenberg.org/files/1342/1342-h/1342-h.htm) to the variable `raw_text`. \n",
    "\n",
    "**Note**: Due to hardware constraints, we'll only use the full text from **Chapter 1** which we've indexed and saved to the variable `raw_text_ch1`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f5210f6d",
   "metadata": {
    "editable": false,
    "tags": [
     "setup"
    ]
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "It is a truth universally acknowledged, that a single man in possession\n",
      "of a good fortune, must be in want of a wife.\n"
     ]
    }
   ],
   "source": [
    "with open('datasets/book.txt', 'r', encoding='utf-8') as f:\n",
    "    raw_text = f.read()\n",
    "\n",
    "# index chapter 1\n",
    "raw_text_ch1 = raw_text[1985:6468]\n",
    "print(raw_text_ch1[:117])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7a8c74d0",
   "metadata": {},
   "source": [
    "Let's tokenize and preprocess the text of Chapter 1 into the following variables:\n",
    "\n",
    "- `tokenized_text` : contains the tokenized text as character-based tokens\n",
    "- `unique_character_tokens` : contains a list of unique tokens sorted by alphabetical order\n",
    "- `c2ix` : the vocabulary as a dictionary mapping the tokens to their token IDs\n",
    "- `ix2c` : the inverse vocabulary mapping the token IDs back to their tokens\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "b318baec",
   "metadata": {
    "deletable": false,
    "tags": [
     "cp1"
    ]
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Vocabulary size: 51\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{0: '\\n',\n",
       " 1: ' ',\n",
       " 2: '!',\n",
       " 3: '\"',\n",
       " 4: ',',\n",
       " 5: '.',\n",
       " 6: ';',\n",
       " 7: '?',\n",
       " 8: 'A',\n",
       " 9: 'B',\n",
       " 10: 'D',\n",
       " 11: 'E',\n",
       " 12: 'H',\n",
       " 13: 'I',\n",
       " 14: 'J',\n",
       " 15: 'L',\n",
       " 16: 'M',\n",
       " 17: 'N',\n",
       " 18: 'O',\n",
       " 19: 'P',\n",
       " 20: 'S',\n",
       " 21: 'T',\n",
       " 22: 'W',\n",
       " 23: 'Y',\n",
       " 24: '_',\n",
       " 25: 'a',\n",
       " 26: 'b',\n",
       " 27: 'c',\n",
       " 28: 'd',\n",
       " 29: 'e',\n",
       " 30: 'f',\n",
       " 31: 'g',\n",
       " 32: 'h',\n",
       " 33: 'i',\n",
       " 34: 'j',\n",
       " 35: 'k',\n",
       " 36: 'l',\n",
       " 37: 'm',\n",
       " 38: 'n',\n",
       " 39: 'o',\n",
       " 40: 'p',\n",
       " 41: 'q',\n",
       " 42: 'r',\n",
       " 43: 's',\n",
       " 44: 't',\n",
       " 45: 'u',\n",
       " 46: 'v',\n",
       " 47: 'w',\n",
       " 48: 'x',\n",
       " 49: 'y',\n",
       " 50: 'z'}"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "tokenized_text = list(raw_text_ch1)\n",
    "unique_character_tokens = sorted(list(set(tokenized_text)))\n",
    "c2ix = {w2ix:ix for ix, w2ix in enumerate(unique_character_tokens)}\n",
    "ix2c = {ix:w for w, ix in c2ix.items()}\n",
    "\n",
    "# Get the vocabulary size\n",
    "vocab_size = len(c2ix)\n",
    "\n",
    "# show output - print the vocabulary size\n",
    "print(\"Vocabulary size:\", vocab_size)\n",
    "ix2c"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "3858a686",
   "metadata": {
    "deletable": false,
    "tags": [
     "cp2"
    ]
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[13,\n",
       " 44,\n",
       " 1,\n",
       " 33,\n",
       " 43,\n",
       " 1,\n",
       " 25,\n",
       " 1,\n",
       " 44,\n",
       " 42,\n",
       " 45,\n",
       " 44,\n",
       " 32,\n",
       " 1,\n",
       " 45,\n",
       " 38,\n",
       " 33,\n",
       " 46,\n",
       " 29,\n",
       " 42,\n",
       " 43,\n",
       " 25,\n",
       " 36,\n",
       " 36,\n",
       " 49,\n",
       " 1,\n",
       " 25,\n",
       " 27,\n",
       " 35,\n",
       " 38,\n",
       " 39,\n",
       " 47,\n",
       " 36,\n",
       " 29,\n",
       " 28,\n",
       " 31,\n",
       " 29,\n",
       " 28,\n",
       " 4,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 25,\n",
       " 44,\n",
       " 1,\n",
       " 25,\n",
       " 1,\n",
       " 43,\n",
       " 33,\n",
       " 38,\n",
       " 31,\n",
       " 36,\n",
       " 29,\n",
       " 1,\n",
       " 37,\n",
       " 25,\n",
       " 38,\n",
       " 1,\n",
       " 33,\n",
       " 38,\n",
       " 1,\n",
       " 40,\n",
       " 39,\n",
       " 43,\n",
       " 43,\n",
       " 29,\n",
       " 43,\n",
       " 43,\n",
       " 33,\n",
       " 39,\n",
       " 38,\n",
       " 0,\n",
       " 39,\n",
       " 30,\n",
       " 1,\n",
       " 25,\n",
       " 1,\n",
       " 31,\n",
       " 39,\n",
       " 39,\n",
       " 28,\n",
       " 1,\n",
       " 30,\n",
       " 39,\n",
       " 42,\n",
       " 44,\n",
       " 45,\n",
       " 38,\n",
       " 29,\n",
       " 4,\n",
       " 1,\n",
       " 37,\n",
       " 45,\n",
       " 43,\n",
       " 44,\n",
       " 1,\n",
       " 26,\n",
       " 29,\n",
       " 1,\n",
       " 33,\n",
       " 38,\n",
       " 1,\n",
       " 47,\n",
       " 25,\n",
       " 38,\n",
       " 44,\n",
       " 1,\n",
       " 39,\n",
       " 30,\n",
       " 1,\n",
       " 25,\n",
       " 1,\n",
       " 47,\n",
       " 33,\n",
       " 30,\n",
       " 29,\n",
       " 5,\n",
       " 0,\n",
       " 0,\n",
       " 12,\n",
       " 39,\n",
       " 47,\n",
       " 29,\n",
       " 46,\n",
       " 29,\n",
       " 42,\n",
       " 1,\n",
       " 36,\n",
       " 33,\n",
       " 44,\n",
       " 44,\n",
       " 36,\n",
       " 29,\n",
       " 1,\n",
       " 35,\n",
       " 38,\n",
       " 39,\n",
       " 47,\n",
       " 38,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 29,\n",
       " 1,\n",
       " 30,\n",
       " 29,\n",
       " 29,\n",
       " 36,\n",
       " 33,\n",
       " 38,\n",
       " 31,\n",
       " 43,\n",
       " 1,\n",
       " 39,\n",
       " 42,\n",
       " 1,\n",
       " 46,\n",
       " 33,\n",
       " 29,\n",
       " 47,\n",
       " 43,\n",
       " 1,\n",
       " 39,\n",
       " 30,\n",
       " 1,\n",
       " 43,\n",
       " 45,\n",
       " 27,\n",
       " 32,\n",
       " 1,\n",
       " 25,\n",
       " 1,\n",
       " 37,\n",
       " 25,\n",
       " 38,\n",
       " 1,\n",
       " 37,\n",
       " 25,\n",
       " 49,\n",
       " 1,\n",
       " 26,\n",
       " 29,\n",
       " 1,\n",
       " 39,\n",
       " 38,\n",
       " 1,\n",
       " 32,\n",
       " 33,\n",
       " 43,\n",
       " 0,\n",
       " 30,\n",
       " 33,\n",
       " 42,\n",
       " 43,\n",
       " 44,\n",
       " 1,\n",
       " 29,\n",
       " 38,\n",
       " 44,\n",
       " 29,\n",
       " 42,\n",
       " 33,\n",
       " 38,\n",
       " 31,\n",
       " 1,\n",
       " 25,\n",
       " 1,\n",
       " 38,\n",
       " 29,\n",
       " 33,\n",
       " 31,\n",
       " 32,\n",
       " 26,\n",
       " 39,\n",
       " 45,\n",
       " 42,\n",
       " 32,\n",
       " 39,\n",
       " 39,\n",
       " 28,\n",
       " 4,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 33,\n",
       " 43,\n",
       " 1,\n",
       " 44,\n",
       " 42,\n",
       " 45,\n",
       " 44,\n",
       " 32,\n",
       " 1,\n",
       " 33,\n",
       " 43,\n",
       " 1,\n",
       " 43,\n",
       " 39,\n",
       " 1,\n",
       " 47,\n",
       " 29,\n",
       " 36,\n",
       " 36,\n",
       " 1,\n",
       " 30,\n",
       " 33,\n",
       " 48,\n",
       " 29,\n",
       " 28,\n",
       " 1,\n",
       " 33,\n",
       " 38,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 29,\n",
       " 1,\n",
       " 37,\n",
       " 33,\n",
       " 38,\n",
       " 28,\n",
       " 43,\n",
       " 0,\n",
       " 39,\n",
       " 30,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 29,\n",
       " 1,\n",
       " 43,\n",
       " 45,\n",
       " 42,\n",
       " 42,\n",
       " 39,\n",
       " 45,\n",
       " 38,\n",
       " 28,\n",
       " 33,\n",
       " 38,\n",
       " 31,\n",
       " 1,\n",
       " 30,\n",
       " 25,\n",
       " 37,\n",
       " 33,\n",
       " 36,\n",
       " 33,\n",
       " 29,\n",
       " 43,\n",
       " 4,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 25,\n",
       " 44,\n",
       " 1,\n",
       " 32,\n",
       " 29,\n",
       " 1,\n",
       " 33,\n",
       " 43,\n",
       " 1,\n",
       " 27,\n",
       " 39,\n",
       " 38,\n",
       " 43,\n",
       " 33,\n",
       " 28,\n",
       " 29,\n",
       " 42,\n",
       " 29,\n",
       " 28,\n",
       " 1,\n",
       " 25,\n",
       " 43,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 29,\n",
       " 1,\n",
       " 42,\n",
       " 33,\n",
       " 31,\n",
       " 32,\n",
       " 44,\n",
       " 30,\n",
       " 45,\n",
       " 36,\n",
       " 0,\n",
       " 40,\n",
       " 42,\n",
       " 39,\n",
       " 40,\n",
       " 29,\n",
       " 42,\n",
       " 44,\n",
       " 49,\n",
       " 1,\n",
       " 39,\n",
       " 30,\n",
       " 1,\n",
       " 43,\n",
       " 39,\n",
       " 37,\n",
       " 29,\n",
       " 1,\n",
       " 39,\n",
       " 38,\n",
       " 29,\n",
       " 1,\n",
       " 39,\n",
       " 42,\n",
       " 1,\n",
       " 39,\n",
       " 44,\n",
       " 32,\n",
       " 29,\n",
       " 42,\n",
       " 1,\n",
       " 39,\n",
       " 30,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 29,\n",
       " 33,\n",
       " 42,\n",
       " 1,\n",
       " 28,\n",
       " 25,\n",
       " 45,\n",
       " 31,\n",
       " 32,\n",
       " 44,\n",
       " 29,\n",
       " 42,\n",
       " 43,\n",
       " 5,\n",
       " 0,\n",
       " 0,\n",
       " 3,\n",
       " 16,\n",
       " 49,\n",
       " 1,\n",
       " 28,\n",
       " 29,\n",
       " 25,\n",
       " 42,\n",
       " 1,\n",
       " 16,\n",
       " 42,\n",
       " 5,\n",
       " 1,\n",
       " 9,\n",
       " 29,\n",
       " 38,\n",
       " 38,\n",
       " 29,\n",
       " 44,\n",
       " 4,\n",
       " 3,\n",
       " 1,\n",
       " 43,\n",
       " 25,\n",
       " 33,\n",
       " 28,\n",
       " 1,\n",
       " 32,\n",
       " 33,\n",
       " 43,\n",
       " 1,\n",
       " 36,\n",
       " 25,\n",
       " 28,\n",
       " 49,\n",
       " 1,\n",
       " 44,\n",
       " 39,\n",
       " 1,\n",
       " 32,\n",
       " 33,\n",
       " 37,\n",
       " 1,\n",
       " 39,\n",
       " 38,\n",
       " 29,\n",
       " 1,\n",
       " 28,\n",
       " 25,\n",
       " 49,\n",
       " 4,\n",
       " 1,\n",
       " 3,\n",
       " 32,\n",
       " 25,\n",
       " 46,\n",
       " 29,\n",
       " 1,\n",
       " 49,\n",
       " 39,\n",
       " 45,\n",
       " 1,\n",
       " 32,\n",
       " 29,\n",
       " 25,\n",
       " 42,\n",
       " 28,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 25,\n",
       " 44,\n",
       " 0,\n",
       " 17,\n",
       " 29,\n",
       " 44,\n",
       " 32,\n",
       " 29,\n",
       " 42,\n",
       " 30,\n",
       " 33,\n",
       " 29,\n",
       " 36,\n",
       " 28,\n",
       " 1,\n",
       " 19,\n",
       " 25,\n",
       " 42,\n",
       " 35,\n",
       " 1,\n",
       " 33,\n",
       " 43,\n",
       " 1,\n",
       " 36,\n",
       " 29,\n",
       " 44,\n",
       " 1,\n",
       " 25,\n",
       " 44,\n",
       " 1,\n",
       " 36,\n",
       " 25,\n",
       " 43,\n",
       " 44,\n",
       " 7,\n",
       " 3,\n",
       " 0,\n",
       " 0,\n",
       " 16,\n",
       " 42,\n",
       " 5,\n",
       " 1,\n",
       " 9,\n",
       " 29,\n",
       " 38,\n",
       " 38,\n",
       " 29,\n",
       " 44,\n",
       " 1,\n",
       " 42,\n",
       " 29,\n",
       " 40,\n",
       " 36,\n",
       " 33,\n",
       " 29,\n",
       " 28,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 25,\n",
       " 44,\n",
       " 1,\n",
       " 32,\n",
       " 29,\n",
       " 1,\n",
       " 32,\n",
       " 25,\n",
       " 28,\n",
       " 1,\n",
       " 38,\n",
       " 39,\n",
       " 44,\n",
       " 5,\n",
       " 0,\n",
       " 0,\n",
       " 3,\n",
       " 9,\n",
       " 45,\n",
       " 44,\n",
       " 1,\n",
       " 33,\n",
       " 44,\n",
       " 1,\n",
       " 33,\n",
       " 43,\n",
       " 4,\n",
       " 3,\n",
       " 1,\n",
       " 42,\n",
       " 29,\n",
       " 44,\n",
       " 45,\n",
       " 42,\n",
       " 38,\n",
       " 29,\n",
       " 28,\n",
       " 1,\n",
       " 43,\n",
       " 32,\n",
       " 29,\n",
       " 6,\n",
       " 1,\n",
       " 3,\n",
       " 30,\n",
       " 39,\n",
       " 42,\n",
       " 1,\n",
       " 16,\n",
       " 42,\n",
       " 43,\n",
       " 5,\n",
       " 1,\n",
       " 15,\n",
       " 39,\n",
       " 38,\n",
       " 31,\n",
       " 1,\n",
       " 32,\n",
       " 25,\n",
       " 43,\n",
       " 1,\n",
       " 34,\n",
       " 45,\n",
       " 43,\n",
       " 44,\n",
       " 1,\n",
       " 26,\n",
       " 29,\n",
       " 29,\n",
       " 38,\n",
       " 1,\n",
       " 32,\n",
       " 29,\n",
       " 42,\n",
       " 29,\n",
       " 4,\n",
       " 1,\n",
       " 25,\n",
       " 38,\n",
       " 28,\n",
       " 1,\n",
       " 43,\n",
       " 32,\n",
       " 29,\n",
       " 0,\n",
       " 44,\n",
       " 39,\n",
       " 36,\n",
       " 28,\n",
       " 1,\n",
       " 37,\n",
       " 29,\n",
       " 1,\n",
       " 25,\n",
       " 36,\n",
       " 36,\n",
       " 1,\n",
       " 25,\n",
       " 26,\n",
       " 39,\n",
       " 45,\n",
       " 44,\n",
       " 1,\n",
       " 33,\n",
       " 44,\n",
       " 5,\n",
       " 3,\n",
       " 0,\n",
       " 0,\n",
       " 16,\n",
       " 42,\n",
       " 5,\n",
       " 1,\n",
       " 9,\n",
       " 29,\n",
       " 38,\n",
       " 38,\n",
       " 29,\n",
       " 44,\n",
       " 1,\n",
       " 37,\n",
       " 25,\n",
       " 28,\n",
       " 29,\n",
       " 1,\n",
       " 38,\n",
       " 39,\n",
       " 1,\n",
       " 25,\n",
       " 38,\n",
       " 43,\n",
       " 47,\n",
       " 29,\n",
       " 42,\n",
       " 5,\n",
       " 0,\n",
       " 0,\n",
       " 3,\n",
       " 10,\n",
       " 39,\n",
       " 1,\n",
       " 38,\n",
       " 39,\n",
       " 44,\n",
       " 1,\n",
       " 49,\n",
       " 39,\n",
       " 45,\n",
       " 1,\n",
       " 47,\n",
       " 25,\n",
       " 38,\n",
       " 44,\n",
       " 1,\n",
       " 44,\n",
       " 39,\n",
       " 1,\n",
       " 35,\n",
       " 38,\n",
       " 39,\n",
       " 47,\n",
       " 1,\n",
       " 47,\n",
       " 32,\n",
       " 39,\n",
       " 1,\n",
       " 32,\n",
       " 25,\n",
       " 43,\n",
       " 1,\n",
       " 44,\n",
       " 25,\n",
       " 35,\n",
       " 29,\n",
       " 38,\n",
       " 1,\n",
       " 33,\n",
       " 44,\n",
       " 7,\n",
       " 3,\n",
       " 1,\n",
       " 27,\n",
       " 42,\n",
       " 33,\n",
       " 29,\n",
       " 28,\n",
       " 1,\n",
       " 32,\n",
       " 33,\n",
       " 43,\n",
       " 1,\n",
       " 47,\n",
       " 33,\n",
       " 30,\n",
       " 29,\n",
       " 1,\n",
       " 33,\n",
       " 37,\n",
       " 40,\n",
       " 25,\n",
       " 44,\n",
       " 33,\n",
       " 29,\n",
       " 38,\n",
       " 44,\n",
       " 36,\n",
       " 49,\n",
       " 5,\n",
       " 0,\n",
       " 0,\n",
       " 3,\n",
       " 24,\n",
       " 23,\n",
       " 39,\n",
       " 45,\n",
       " 24,\n",
       " 1,\n",
       " 47,\n",
       " 25,\n",
       " 38,\n",
       " 44,\n",
       " 1,\n",
       " 44,\n",
       " 39,\n",
       " 1,\n",
       " 44,\n",
       " 29,\n",
       " 36,\n",
       " 36,\n",
       " 1,\n",
       " 37,\n",
       " 29,\n",
       " 4,\n",
       " 1,\n",
       " 25,\n",
       " 38,\n",
       " 28,\n",
       " 1,\n",
       " 13,\n",
       " 1,\n",
       " 32,\n",
       " 25,\n",
       " 46,\n",
       " 29,\n",
       " 1,\n",
       " 38,\n",
       " 39,\n",
       " 1,\n",
       " 39,\n",
       " 26,\n",
       " 34,\n",
       " 29,\n",
       " 27,\n",
       " 44,\n",
       " 33,\n",
       " 39,\n",
       " 38,\n",
       " 1,\n",
       " 44,\n",
       " 39,\n",
       " 1,\n",
       " 32,\n",
       " 29,\n",
       " 25,\n",
       " 42,\n",
       " 33,\n",
       " 38,\n",
       " 31,\n",
       " 1,\n",
       " 33,\n",
       " 44,\n",
       " 5,\n",
       " 3,\n",
       " 0,\n",
       " 0,\n",
       " 21,\n",
       " 32,\n",
       " 33,\n",
       " 43,\n",
       " 1,\n",
       " 47,\n",
       " 25,\n",
       " 43,\n",
       " 1,\n",
       " 33,\n",
       " 38,\n",
       " 46,\n",
       " 33,\n",
       " 44,\n",
       " 25,\n",
       " 44,\n",
       " 33,\n",
       " 39,\n",
       " 38,\n",
       " 1,\n",
       " 29,\n",
       " 38,\n",
       " 39,\n",
       " 45,\n",
       " 31,\n",
       " 32,\n",
       " 5,\n",
       " 0,\n",
       " 0,\n",
       " 3,\n",
       " 22,\n",
       " 32,\n",
       " 49,\n",
       " 4,\n",
       " 1,\n",
       " 37,\n",
       " 49,\n",
       " 1,\n",
       " 28,\n",
       " 29,\n",
       " 25,\n",
       " 42,\n",
       " 4,\n",
       " 1,\n",
       " 49,\n",
       " 39,\n",
       " 45,\n",
       " 1,\n",
       " 37,\n",
       " 45,\n",
       " 43,\n",
       " 44,\n",
       " 1,\n",
       " 35,\n",
       " 38,\n",
       " 39,\n",
       " 47,\n",
       " 4,\n",
       " 1,\n",
       " 16,\n",
       " 42,\n",
       " 43,\n",
       " 5,\n",
       " 1,\n",
       " 15,\n",
       " 39,\n",
       " 38,\n",
       " 31,\n",
       " 1,\n",
       " 43,\n",
       " 25,\n",
       " 49,\n",
       " 43,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 25,\n",
       " 44,\n",
       " 1,\n",
       " 17,\n",
       " 29,\n",
       " 44,\n",
       " 32,\n",
       " 29,\n",
       " 42,\n",
       " 30,\n",
       " 33,\n",
       " 29,\n",
       " 36,\n",
       " 28,\n",
       " 1,\n",
       " 33,\n",
       " 43,\n",
       " 1,\n",
       " 44,\n",
       " 25,\n",
       " 35,\n",
       " 29,\n",
       " 38,\n",
       " 0,\n",
       " 26,\n",
       " 49,\n",
       " 1,\n",
       " 25,\n",
       " 1,\n",
       " 49,\n",
       " 39,\n",
       " 45,\n",
       " 38,\n",
       " 31,\n",
       " 1,\n",
       " 37,\n",
       " 25,\n",
       " 38,\n",
       " 1,\n",
       " 39,\n",
       " 30,\n",
       " 1,\n",
       " 36,\n",
       " 25,\n",
       " 42,\n",
       " 31,\n",
       " 29,\n",
       " 1,\n",
       " 30,\n",
       " 39,\n",
       " 42,\n",
       " 44,\n",
       " 45,\n",
       " 38,\n",
       " 29,\n",
       " 1,\n",
       " 30,\n",
       " 42,\n",
       " 39,\n",
       " 37,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 29,\n",
       " 1,\n",
       " 38,\n",
       " 39,\n",
       " 42,\n",
       " 44,\n",
       " 32,\n",
       " 1,\n",
       " 39,\n",
       " 30,\n",
       " 1,\n",
       " 11,\n",
       " 38,\n",
       " 31,\n",
       " 36,\n",
       " 25,\n",
       " 38,\n",
       " 28,\n",
       " 6,\n",
       " 1,\n",
       " 44,\n",
       " 32,\n",
       " 25,\n",
       " 44,\n",
       " 1,\n",
       " 32,\n",
       " 29,\n",
       " 1,\n",
       " 27,\n",
       " 25,\n",
       " 37,\n",
       " 29,\n",
       " 0,\n",
       " 28,\n",
       " 39,\n",
       " 47,\n",
       " 38,\n",
       " 1,\n",
       " 39,\n",
       " 38,\n",
       " 1,\n",
       " 16,\n",
       " 39,\n",
       " 38,\n",
       " 28,\n",
       " 25,\n",
       " 49,\n",
       " 1,\n",
       " 33,\n",
       " 38,\n",
       " 1,\n",
       " 25,\n",
       " 1,\n",
       " 27,\n",
       " 32,\n",
       " 25,\n",
       " 33,\n",
       " 43,\n",
       " 29,\n",
       " 1,\n",
       " 25,\n",
       " 38,\n",
       " 28,\n",
       " 1,\n",
       " 30,\n",
       " 39,\n",
       " 45,\n",
       " 42,\n",
       " 1,\n",
       " 44,\n",
       " 39,\n",
       " 1,\n",
       " 43,\n",
       " 29,\n",
       " 29,\n",
       " ...]"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "tokenized_id_text = [c2ix[word] for word in tokenized_text]\n",
    "tokenized_id_text"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6a172e5e",
   "metadata": {},
   "source": [
    "Let's now use the PyTorch utility class `Dataset` to prepare the tokenized text into sequences for the features and labels.\n",
    "\n",
    "Finish building the `TextDataset` class that utilizes `Dataset` utility such that:\n",
    "\n",
    "1. In the `init` method, initialize the class attributes:\n",
    "   - `self.tokenized_text` assigned with the input variable `tokenized_text`\n",
    "   - `self.seq_length` assigned with the input variable `seq_length`\n",
    "\n",
    "2. In the `getitem` method, return the feature sequences and labels as PyTorch tensors. The labels are created by shifting the feature sequences by one token to the right.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "e73ed471",
   "metadata": {
    "deletable": false,
    "tags": [
     "cp3"
    ]
   },
   "outputs": [],
   "source": [
    "from torch.utils.data import Dataset, DataLoader\n",
    "\n",
    "class TextDataset(Dataset):\n",
    "    def __init__(self, tokenized_text, seq_length):\n",
    "        self.tokenized_text = tokenized_text\n",
    "        self.seq_length = seq_length\n",
    "        \n",
    "    def __len__(self):\n",
    "        return len(self.tokenized_text) - self.seq_length\n",
    "        \n",
    "    def __getitem__(self, idx):\n",
    "        features =torch.tensor(self.tokenized_text[idx:idx+self.seq_length])\n",
    "        labels =torch.tensor(self.tokenized_text[idx+1:idx+self.seq_length+1])\n",
    "        return features, labels"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8d481799",
   "metadata": {},
   "source": [
    "\n",
    "Now that the dataset class is built, let's access the features and labels to be loaded as batches.\n",
    "\n",
    "1. Create and access the sequences for the features and labels.\n",
    "   - Specify a sequence length of `24` and save the value to the variable `seq_length`\n",
    "   - Use the created `TextDataset` class to create the features and labels from the tokenized text using the sequence length. Save the sequences to the variable `dataset`. \n",
    "\n",
    "2. Create the iterable that allows us to load the sequences as batches.\n",
    "   - Specify a batch size of `48` and save the value to the variable `batch_size`\n",
    "   - Use the `DataLoader` utility class by inputting the dataset, batch size, and setting shuffle to `True`. Save the iterable to the variable `dataloader`.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "4ddf801b",
   "metadata": {
    "deletable": false,
    "tags": [
     "cp4"
    ]
   },
   "outputs": [],
   "source": [
    "torch.manual_seed(1) # set random seed \n",
    "\n",
    "seq_length = 24\n",
    "dataset = TextDataset(tokenized_id_text,seq_length)\n",
    "\n",
    "batch_size = 48\n",
    "dataloader = DataLoader(dataset,batch_size=batch_size, shuffle=True )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "380d2ab4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<torch.utils.data.dataloader.DataLoader at 0x7fb448079bd0>"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dataloader"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
